export const USER_LOGOUT = 'USER_LOGOUT';

export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_STOP = 'FETCH_CURRENT_USER_STOP';
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_TOKEN = 'SET_TOKEN';
